#!/usr/bin/env zsh
#
set -x

sudo /opt/homebrew/bin/yabai --load -sa
/opt/homebrew/bin/yabai -m signal --add event=dock_dit_restart action="sudo /opt/homebrew/bin/yabai --load-sa"

/opt/homebrew/bin/yabai -m config layout bsp
/opt/homebrew/bin/yabai -m config top_padding 5 
/opt/homebrew/bin/yabai -m config bottom_padding 5
/opt/homebrew/bin/yabai -m config left_padding 5 
/opt/homebrew/bin/yabai -m config right_padding 5 
/opt/homebrew/bin/yabai -m config window_gap 5

# float some applications
yabai -m rule --add app='Finder' manage=off
yabai -m rule --add app='WeChat' manage=off
yabai -m rule --add app='QQ' manage=off
yabai -m rule --add app='python' manage=off
# yabai -m rule --add app='Skim' manage=off
yabai -m rule --add app='R2020a' manage=off
yabai -m rule --add app='Arc' manage=off
yabai -m rule --add app='zoom' manage=off

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
# sketchybar in multi monitor
# yabai -m config external_bar all:0:0

# borders active_color=0xffC678DD inactive_color=0xff494d64 width=5.0 &


echo "yabai configuration loaded .."
