local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
	require("user.editor"),
	require("user.bufferline"),
	require("user.cmp"),
	require("user.code"),
	require("user.comment"),
	require("user.colorizer"),
	require("user.copilot"),
	require("user.debug"),
	require("user.edge"),
	require("user.flash"),
	require("user.formatter"),
	require("user.indent"),
	-- require("user.ghostline"),
	require("user.git"),
	require("user.leetcode"),
	require("user.lsp"),
	require("user.lualine"),
	-- require("user.eviline"),
	require("user.markdown"),
	require("user.neotree"),
	require("user.neodev"),
	-- require("user.noice"),
	require("user.project"),
	require("user.python"),
	require("user.rainbow_pair"),
	require("user.tex"),
	require("user.terminal"),
	require("user.telescope"),
	--- colorschemes
	-- require("user.theme.cyberdream"),
	-- require("user.theme.tender"),
	-- require("user.theme.kurayami"),
	-- require("user.theme.nightfox"),
	-- require("user.theme.material"),
	-- require("user.theme.alabaster"),
	-- require("user.theme.onedark"),
	-- require("user.theme.bamboo"),
	-- require("user.theme.code"),
	-- require("user.theme.dracula"),
	-- require("user.theme.default"),
	-- require("user.theme.deus"),
	-- require("user.theme.kanagawa"),
	-- require("user.theme.rose-pine"),
	-- require("user.theme.tokyonight"),
	require("user.theme.catppuccin"),
	-- require("user.theme.vague"),
	-- require("user.theme.gruvbox"),
	-- require("user.theme.solarized"),
	-- require("user.theme.moon-fly"),
	-- require("user.theme.green"),
	-- require("user.theme.leaf"),
	-- require("user.theme.zenbones"),
	-- require("user.theme.spaceduck"),
	-- require("user.theme.darker"),
	---
	require("user.ui"),
	require("user.winbar"),
	require("user.yazi"),
})
